- name: Apache - support TLS 1.2 and 1.3 only
  lineinfile:
    dest: "/etc/apache2/mods-available/ssl.conf"
    regexp: "SSLProtocol"
    line: "SSLProtocol -all +TLSv1.3 +TLSv1.2"
  notify: restart apache
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version >= '10') or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= '20')

- name: Apache - support TLS 1.2 only
  lineinfile:
    dest: "/etc/apache2/mods-available/ssl.conf"
    regexp: "SSLProtocol"
    line: "SSLProtocol -all +TLSv1.3 +TLSv1.2"
  notify: restart apache
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version < '10') or (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version < '20')

- name: Enable proxy_http (for stage_file_proxy-like image redirects)
  community.general.apache2_module:
    state: present
    name: proxy_http
