- name: Apache - support TLS 1.2 and 1.3 only
  lineinfile:
    dest: "/etc/apache2/mods-available/ssl.conf"
    regexp: "SSLProtocol"
    line: "SSLProtocol -all +TLSv1.3 +TLSv1.2"
  notify: restart apache

- name: Enable proxy_http (for stage_file_proxy-like image redirects)
  community.general.apache2_module:
    state: present
    name: proxy_http

- name: Block bots at the conf level
  ansible.builtin.template:
    src: "templates/blocked-agents.conf.j2"
    dest: "/etc/apache2/conf-available/blocked-agents.conf"
  notify: restart apache

- name: Enable blocked-agents.conf
  command: a2enconf blocked-agents

- name: Enable headers module (for secure headers)
  community.general.apache2_module:
    state: present
    name: headers

- name: Harden Apache - reduce header info, CSP, HSTS, etc.
  ansible.builtin.template:
    src: "templates/security.conf.j2"
    dest: "/etc/apache2/conf-available/security.conf"
  notify: restart apache
  # FIXME: Temp tag until this is on all my servers.
  tags: apache-headers

- name: Enable blocked-agents.conf
  command: a2enconf security
